version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "video-genesis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-183tuxfhh6tm2"
s3_prefix = "video-genesis"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
